apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-service
  template:
    metadata:
      labels:
        app: expense-service
    spec:
      containers:
      - name: expense-service
        image: masum140/expence:backend-expense-v1
        ports:
        - containerPort: 5000

